Repository TeamTalkable/ANDROID, pull requests merged in 2024-11, with the labels that each got.

#86 [Feature/#85] : TTS 자동 실행 구현
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
Labels: ⭐ [FEAT], 🐰 유진,  ♻️ [REFACTOR]

#88 Feature : 자동 로그인, 카카오 닉네임
  app/src/main/java/com/talkable/data/SharedManager.kt
  app/src/main/java/com/talkable/presentation/MainActivity.kt
  app/src/main/java/com/talkable/presentation/SplashActivity.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/home/HomeFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 🐱 소현, ⭐ [FEAT]

#91 [Feature/#90] 복습하기 페이지 UI
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedFragment.kt
  app/src/main/java/com/talkable/presentation/home/HomeFragment.kt
  app/src/main/java/com/talkable/presentation/home/TalkFeedbackDecorator.kt
  app/src/main/java/com/talkable/presentation/home/TalkReviewFragment.kt
  app/src/main/java/com/talkable/presentation/home/TalkReviewTopAdapter.kt
  app/src/main/java/com/talkable/presentation/home/viewholder/TalkReviewTopViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_talk_review.xml
  app/src/main/res/layout/item_talk_feedback_learned_expression.xml
  app/src/main/res/layout/item_talk_feedback_learned_grammar.xml
  app/src/main/res/layout/item_talk_review.xml
  app/src/main/res/layout/view_review_app_bar.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐰 유진, 💟 [UI]

#93 [Feature/#92] : 힌트 다이얼로그 수정
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkHintDialog.kt
  app/src/main/res/drawable-xhdpi/ic_talk_hint.png
  app/src/main/res/drawable-xxhdpi/ic_talk_hint.png
  app/src/main/res/drawable/ic_talk_help.xml
  app/src/main/res/drawable/ic_talk_hint.png
  app/src/main/res/drawable/ic_talk_hint_close.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/toast_talk_hint.xml
Labels: 🐰 유진, 💟 [UI]

#94 [Feature/#89] : today feedback 데이터 연동, 학습 시간 받아오기
  app/src/main/java/com/talkable/core/type/RoleType.kt
  app/src/main/java/com/talkable/data/FirebaseFactory.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackTopViewHolder.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: 🐱 소현, ⭐ [FEAT]

#97 [Fix/#95] : 안내 문구 visibility 제어
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/values/colors.xml
Labels: 🔨 [FIX], 🐰 유진

#100 [Feature/#99] : 단어 및 구문 저장
  app/src/main/java/com/talkable/data/FirebaseFactory.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedListFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedViewHolder.kt
  app/src/main/java/com/talkable/presentation/feedback/today/model/TodaySaved.kt
  app/src/main/java/com/talkable/presentation/feedback/today/model/TodaySavedModel.kt
  app/src/main/java/com/talkable/presentation/home/HomeFragment.kt
  app/src/main/java/com/talkable/presentation/home/TalkReviewFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedSyntaxAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedSyntaxFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedSyntaxViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/model/SavedListModel.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/model/SavedWordViewModel.kt
  app/src/main/java/com/talkable/presentation/review/ReviewFragment.kt
  app/src/main/java/com/talkable/presentation/review/model/SavedViewModel.kt
  app/src/main/java/com/talkable/presentation/review/model/TalkSavedModel.kt
  app/src/main/java/com/talkable/presentation/review/model/TodaySavedViewModel.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/layout/fragment_saved_word.xml
  app/src/main/res/layout/item_home_calendar.xml
  app/src/main/res/layout/item_today_saved.xml
  app/src/main/res/layout/view_my_page_app_bar.xml
  app/src/main/res/layout/view_saved_sort.xml
  app/src/main/res/layout/view_talk_feedback_part.xml
  app/src/main/res/menu/menu_save_text.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 🐰 유진
