Repository TeamTalkable/ANDROID, pull requests merged in 2024-08, with the labels that each got.

#45 [Feature/#44] : 오늘 저장한 목록/피드백
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackViewHolder.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedCategory.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedListFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedPagerAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodaySavedViewHolder.kt
  app/src/main/java/com/talkable/presentation/feedback/today/model/TodayFeedbackModel.kt
  app/src/main/java/com/talkable/presentation/feedback/today/model/TodaySavedModel.kt
  app/src/main/res/color/sel_today_expression_chip_bg.xml
  app/src/main/res/color/sel_today_grammar_chip_bg.xml
  app/src/main/res/color/sel_today_pronunciation_chip_bg.xml
  app/src/main/res/drawable/shape_font4_fill_circle.xml
  app/src/main/res/drawable/shape_grammar_bg_fill_12_rect.xml
  app/src/main/res/drawable/shape_pronunciation_bg_fill_12_rect.xml
  app/src/main/res/layout/fragment_my_feedback_expression.xml
  app/src/main/res/layout/fragment_my_feedback_grammar.xml
  app/src/main/res/layout/fragment_today_feedback.xml
  app/src/main/res/layout/fragment_today_saved.xml
  app/src/main/res/layout/fragment_today_saved_list.xml
  app/src/main/res/layout/item_my_feedback_expression.xml
  app/src/main/res/layout/item_my_feedback_grammar.xml
  app/src/main/res/layout/item_today_feedback.xml
  app/src/main/res/layout/item_today_feedback_expression.xml
  app/src/main/res/layout/item_today_feedback_grammar.xml
  app/src/main/res/layout/item_today_feedback_pronunciation.xml
  app/src/main/res/layout/item_today_feedback_pronunciation_graph.xml
  app/src/main/res/layout/item_today_saved.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐰 유진, 💟 [UI]

#47 [Feature/#43] : today quize UI
  app/build.gradle.kts
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/core/util/fragment/FragmentExt.kt
  app/src/main/java/com/talkable/core/view/ChartView.kt
  app/src/main/java/com/talkable/presentation/home/HomeFragment.kt
  app/src/main/java/com/talkable/presentation/myflower/MyFlowerFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageChartDetailFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/model/MyPageModel.kt
  app/src/main/java/com/talkable/presentation/onboarding/OnboardingFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizAutoFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizFlashFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizSpellingMeaningFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/TodayQuizDialog.kt
  app/src/main/res/drawable/ic_today_quiz_bad.xml
  app/src/main/res/drawable/ic_today_quiz_good.xml
  app/src/main/res/layout/dialog_today_quiz.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_flower.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_chart_detail.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_quiz_spelling_meaning.xml
  app/src/main/res/layout/fragment_setting_alarm.xml
  app/src/main/res/layout/item_my_page_calendar.xml
  app/src/main/res/layout/view_my_flower_progress.xml
  app/src/main/res/layout/view_quiz_flash_auto_card.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🐱 소현, 💟 [UI]

#48 [Fix/#46] : QA 반영
  app/src/main/res/layout/fragment_agreement.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/item_challenge_recruitment.xml
  app/src/main/res/layout/item_home_calendar.xml
Labels: 🐰 유진, 💟 [UI]

#50 [Feature/#49] : second qa
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/model/FeedbackExpressionModel.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageChartDetailFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/onboarding/AlarmSettingFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizAutoSpeedBottomSheet.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackLearnedPronunciationViewHolder.kt
  app/src/main/res/layout/bottom_sheet_quiz_auto_speed.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/lottie_feedback_loading.json
  app/src/main/res/raw/lottie_pronunciation.json
  app/src/main/res/raw/science.mp3
  app/src/main/res/raw/science_user.mp3
  app/src/main/res/raw/today.mp3
  app/src/main/res/raw/today_user.mp3
  gradle/libs.versions.toml
Labels: 🐱 소현,  ♻️ [REFACTOR]

#52 [Feature/#51] : 2차 QA 반영
  app/src/main/java/com/talkable/presentation/MainActivity.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackDecorator.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackGrammarFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedSyntaxViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/FeedbackRetryDialog.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFeedbackDialog.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable/ic_saved_listen_unselected.xml
  app/src/main/res/drawable/ic_talk_listen_selected.xml
  app/src/main/res/drawable/ic_talk_listen_unselected.xml
  app/src/main/res/drawable/sel_saved_listen_selected.xml
  app/src/main/res/drawable/sel_talk_listen_selected.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_feedback_retry_dialog.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_talk_feedback_dialog.xml
  app/src/main/res/layout/item_challenge_participation.xml
  app/src/main/res/layout/item_my_feedback_expression.xml
  app/src/main/res/layout/item_my_feedback_grammar.xml
  app/src/main/res/layout/item_my_feedback_pronunciation.xml
  app/src/main/res/layout/item_saved_syntax.xml
  app/src/main/res/layout/item_saved_word.xml
  app/src/main/res/layout/item_today_feedback.xml
  app/src/main/res/layout/item_today_feedback_expression.xml
  app/src/main/res/layout/item_today_feedback_grammar.xml
  app/src/main/res/layout/view_talk_speech.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐰 유진,  ♻️ [REFACTOR]
