Repository TeamTalkable/ANDROID, pull requests merged in 2024-06, with the labels that each got.

#12 [Feature/#9] : mypage UI
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/talkable/TalkableApp.kt
  app/src/main/java/com/talkable/core/util/BindingAdapter.kt
  app/src/main/java/com/talkable/core/view/ChartView.kt
  app/src/main/java/com/talkable/presentation/MainActivity.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/model/MyPageModel.kt
  app/src/main/res/color/sel_nav_text.xml
  app/src/main/res/drawable/ic_my_page_indicator.xml
  app/src/main/res/drawable/ic_my_page_my_flower_navigate.xml
  app/src/main/res/drawable/shape_fill_main3_8_rec.xml
  app/src/main/res/drawable/shape_font4_line_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_talk_feedback_learned_expression.xml
  app/src/main/res/layout/item_talk_feedback_learned_grammar.xml
  app/src/main/res/layout/item_talk_feedback_learned_pronunciation.xml
  app/src/main/res/layout/view_my_page_day_calender.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
  app/src/main/res/values/themes.xml
Labels: 🐱 소현, 💟 [UI]

#20 [Feature/#17] Challenge UI
  app/src/main/java/com/talkable/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeParticipationAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeRecruitmentAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/Participation.kt
  app/src/main/java/com/talkable/presentation/challenge/ParticipationViewHolder.kt
  app/src/main/java/com/talkable/presentation/challenge/Ranking.kt
  app/src/main/java/com/talkable/presentation/challenge/RankingAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/RankingItemDecorator.kt
  app/src/main/java/com/talkable/presentation/challenge/RankingViewHolder.kt
  app/src/main/java/com/talkable/presentation/challenge/Recruitment.kt
  app/src/main/java/com/talkable/presentation/challenge/RecruitmentViewHolder.kt
  app/src/main/res/drawable-xhdpi/img_challenge_fertilizer.png
  app/src/main/res/drawable-xhdpi/img_challenge_medicine.png
  app/src/main/res/drawable-xhdpi/img_challenge_secret.png
  app/src/main/res/drawable-xhdpi/img_challenge_shovel.png
  app/src/main/res/drawable-xhdpi/img_challenge_sun.png
  app/src/main/res/drawable-xhdpi/img_challenge_water.png
  app/src/main/res/drawable-xhdpi/img_challenge_wind.png
  app/src/main/res/drawable-xxhdpi/img_challenge_fertilizer.png
  app/src/main/res/drawable-xxhdpi/img_challenge_medicine.png
  app/src/main/res/drawable-xxhdpi/img_challenge_secret.png
  app/src/main/res/drawable-xxhdpi/img_challenge_shovel.png
  app/src/main/res/drawable-xxhdpi/img_challenge_sun.png
  app/src/main/res/drawable-xxhdpi/img_challenge_water.png
  app/src/main/res/drawable-xxhdpi/img_challenge_wind.png
  app/src/main/res/drawable/ic_challenge_next.xml
  app/src/main/res/drawable/img_challenge_fertilizer.png
  app/src/main/res/drawable/img_challenge_medicine.png
  app/src/main/res/drawable/img_challenge_secret.png
  app/src/main/res/drawable/img_challenge_shovel.png
  app/src/main/res/drawable/img_challenge_sun.png
  app/src/main/res/drawable/img_challenge_water.png
  app/src/main/res/drawable/img_challenge_wind.png
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/item_challenge_participation.xml
  app/src/main/res/layout/item_challenge_ranking.xml
  app/src/main/res/layout/item_challenge_recruitment.xml
  app/src/main/res/layout/view_challenge_ranking.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 유진, 💟 [UI]

#22 [Feature/#16] : feedback UI 구현
  app/src/main/java/com/talkable/core/base/BindingDialogFragment.kt
  app/src/main/java/com/talkable/core/util/context/ContextExt.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationCompleteDialog.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationWordAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/model/FeedbackExpressionModel.kt
  app/src/main/java/com/talkable/presentation/feedback/viewholder/PronunciationWordViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackLearnedPronunciationViewHolder.kt
  app/src/main/res/color/sel_pronunciation_word_text.xml
  app/src/main/res/drawable/gradient_feedback_pronunciation_progressbar.xml
  app/src/main/res/drawable/ic_feedback_arrow_down.xml
  app/src/main/res/drawable/ic_feedback_check.xml
  app/src/main/res/drawable/ic_feedback_mick.xml
  app/src/main/res/drawable/ic_feedback_trash.xml
  app/src/main/res/drawable/ic_talk_ai_voice.xml
  app/src/main/res/drawable/ic_talk_feedback_bookmark.xml
  app/src/main/res/drawable/ic_talk_user_voice.xml
  app/src/main/res/drawable/sel_pronunciation_word_bg.xml
  app/src/main/res/drawable/shape_font4_fill_40_rect.xml
  app/src/main/res/drawable/shape_gray2_fill_top_12_rec.xml
  app/src/main/res/drawable/shape_gray_2_fill_12_rect.xml
  app/src/main/res/layout/bottom_sheet_talk_feedback.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_feedback_pronunciation_complete_dialog.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/layout/item_pronunciation_word.xml
  app/src/main/res/layout/item_talk_feedback_learned_label.xml
  app/src/main/res/layout/item_talk_feedback_learned_pronunciation.xml
  app/src/main/res/layout/view_talk_feedback_app_bar.xml
  app/src/main/res/menu/menu_feedback.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/lottie_pronunciation.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐱 소현, 💟 [UI]

#25 [Feature/#9] : my page tab 막대 차트 ui
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/talkable/core/util/BindingAdapter.kt
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/core/view/BarGraphView.kt
  app/src/main/java/com/talkable/presentation/FeedbackTextColor.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageBarChartAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageBarChartDecorator.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageChartDetailFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/model/MyPageModel.kt
  app/src/main/java/com/talkable/presentation/mypage/viewholder/MyPageBarChartViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackDecorator.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackLearnedAdapter.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/mapper/TalkFeedbackMapper.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackLearnedAfterAnswerViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackLearnedPronunciationViewHolder.kt
  app/src/main/res/color/sel_icon.xml
  app/src/main/res/color/sel_my_page_chart_detail_chip_bg.xml
  app/src/main/res/drawable/ic_my_page_cancel.xml
  app/src/main/res/drawable/shape_fill_white_bottom_12_rec.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_chart_detail.xml
  app/src/main/res/layout/fragment_talk_feedback.xml
  app/src/main/res/layout/item_my_page_bar_chart.xml
  app/src/main/res/layout/item_talk_feedback_learned_after_sentence.xml
  app/src/main/res/layout/item_talk_feedback_learned_expression.xml
  app/src/main/res/layout/item_talk_feedback_learned_grammar.xml
  app/src/main/res/layout/item_talk_feedback_learned_label.xml
  app/src/main/res/layout/item_talk_feedback_learned_pronunciation.xml
  app/src/main/res/layout/item_talk_feedback_top.xml
  app/src/main/res/layout/view_my_page_bar_graph.xml
  app/src/main/res/layout/view_talk_feedback_app_bar.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐱 소현, 💟 [UI]

#27 [Feature/#21] mypage feedback UI
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyExpressionAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackDialogFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackGrammarFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackViewPagerAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyGrammarAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyPronunciationAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/data/Expression.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/data/Grammar.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/viewholder/MyFeedbackExpressionViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/viewholder/MyFeedbackGrammarViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/viewholder/MyFeedbackPronunciationViewHolder.kt
  app/src/main/res/drawable/ic_feedback_write.xml
  app/src/main/res/drawable/ic_my_feedback_category_selected.xml
  app/src/main/res/drawable/ic_my_feedback_category_unselected.xml
  app/src/main/res/drawable/ic_my_feedback_initialization.xml
  app/src/main/res/drawable/ic_my_feedback_search.xml
  app/src/main/res/drawable/sel_my_feedback_btn.xml
  app/src/main/res/drawable/sel_my_feedback_category.xml
  app/src/main/res/drawable/sel_my_feedback_txt_color.xml
  app/src/main/res/drawable/shape_font5_line_rect.xml
  app/src/main/res/drawable/shape_font_line_rect.xml
  app/src/main/res/layout/fragment_my_feedback_dialog.xml
  app/src/main/res/layout/fragment_my_feedback_expression.xml
  app/src/main/res/layout/fragment_my_feedback_grammar.xml
  app/src/main/res/layout/fragment_my_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_my_page_feedback.xml
  app/src/main/res/layout/item_my_feedback_expression.xml
  app/src/main/res/layout/item_my_feedback_grammar.xml
  app/src/main/res/layout/item_my_feedback_pronunciation.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐰 유진, 💟 [UI]

#30 [Feature/#23] talk UI 수정
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable/ic_talk_speech_check.xml
  app/src/main/res/drawable/shape_speech_fill_12_top_rect.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/view_talk_speech.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: ✅ [MOD], 🐰 유진

#31 [Mod/#23] 챌린지 UI 수정
  app/src/main/java/com/talkable/presentation/challenge/ChallengeDialog.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/talkable/presentation/challenge/RecruitmentViewHolder.kt
  app/src/main/res/drawable/shape_brown_line_circle.xml
  app/src/main/res/layout/dialog_challenge.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/item_challenge_participation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐰 유진, 💟 [UI]

#32 [Feature/#29] : 뷰 연결
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/login/AgreementFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageChartDetailFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackBottomAdapter.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/viewholder/TalkFeedbackBottomViewHolder.kt
  app/src/main/res/drawable-xhdpi/ic_login.png
  app/src/main/res/drawable-xhdpi/logo_talkable.png
  app/src/main/res/drawable-xxhdpi/ic_login.png
  app/src/main/res/drawable-xxhdpi/logo_talkable.png
  app/src/main/res/drawable-xxxhdpi/ic_login.png
  app/src/main/res/drawable/ic_login.png
  app/src/main/res/drawable/logo_talkable.png
  app/src/main/res/layout/fragment_my_page_chart_detail.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 🐱 소현, ⭐ [FEAT]

#33 [Mod/#23] QA 반영
  app/src/main/java/com/talkable/presentation/login/AgreementFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/viewholder/MyFeedbackPronunciationViewHolder.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable/ic_talk_listen.xml
  app/src/main/res/drawable/ic_talk_show_unselected.xml
  app/src/main/res/drawable/ic_talk_translate_unselected.xml
  app/src/main/res/drawable/sel_agreement_selected_next.xml
  app/src/main/res/drawable/shape_font4_fill_12_rect.xml
  app/src/main/res/drawable/shape_main3_line_2_rect.xml
  app/src/main/res/layout/fragment_agreement.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_my_feedback_expression.xml
  app/src/main/res/layout/fragment_my_feedback_grammar.xml
  app/src/main/res/layout/fragment_my_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_my_page_feedback.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/item_challenge_ranking.xml
  app/src/main/res/layout/item_home_calendar.xml
  app/src/main/res/layout/item_my_feedback_expression.xml
  app/src/main/res/layout/item_my_feedback_grammar.xml
  app/src/main/res/layout/item_my_feedback_pronunciation.xml
  app/src/main/res/layout/toast_talk_hint.xml
  app/src/main/res/values/style.xml
Labels: 🐰 유진, 💟 [UI]

#35 [Fix/#34] : 마이 페이지, 피드백 뷰 QA
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/layout/item_talk_feedback_learned_expression.xml
  app/src/main/res/layout/item_talk_feedback_learned_grammar.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐱 소현, 🔨 [FIX]
