Repository TeamTalkable/ANDROID, pull requests merged in 2024-09, with the labels that each got.

#55 [Feature/#53] : 3차 QA 반영
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/today/TodayFeedbackViewHolder.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/Constants.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedSyntaxFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable-xhdpi/ic_talk_folder.png
  app/src/main/res/drawable-xxhdpi/ic_talk_folder.png
  app/src/main/res/drawable/bg_talk_gradient.png
  app/src/main/res/drawable/bg_talk_speech_bubble.xml
  app/src/main/res/drawable/ic_feedback_close.xml
  app/src/main/res/drawable/ic_feedback_open.xml
  app/src/main/res/drawable/ic_talk_folder.png
  app/src/main/res/drawable/sel_talk_feedback.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_today_feedback.xml
  app/src/main/res/layout/item_my_feedback_expression.xml
  app/src/main/res/layout/item_my_feedback_grammar.xml
  app/src/main/res/layout/item_today_feedback_pronunciation_graph.xml
  app/src/main/res/layout/view_talk_feedback.xml
Labels: 🐰 유진,  ♻️ [REFACTOR]

#56 [Feature/#54] : 퀴즈 결과, 피드백 ui 수정
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizAutoFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizFlashFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizResultFragment.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizSpellingMeaningFragment.kt
  app/src/main/res/drawable/img_quiz_clap.png
  app/src/main/res/layout/bottom_sheet_talk_feedback.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_quiz_result.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐱 소현, ⭐ [FEAT]

#58 [Feature/#57] 챌린지 UI
  app/src/main/java/com/talkable/presentation/challenge/ChallengeDialog.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeRecruitingAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeRecruitingFragment.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeRecruitmentAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/Recruiting.kt
  app/src/main/java/com/talkable/presentation/challenge/RecruitingViewHolder.kt
  app/src/main/java/com/talkable/presentation/challenge/RecruitmentViewHolder.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/sel_challenge_selected.xml
  app/src/main/res/drawable/sel_challenge_txt_color.xml
  app/src/main/res/layout/dialog_challenge.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_challenge_recruiting.xml
  app/src/main/res/layout/item_challenge_recruiting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🐰 유진, 💟 [UI]

#62 [Feature/#60] STT 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/talkable/presentation/talk/FeedbackRetryDialog.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/layout/view_talk_speech.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐰 유진

#63 [Feature/#59] gpt open api 연결
  app/build.gradle.kts
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/data/ApiFactory.kt
  app/src/main/java/com/talkable/data/api/GptApiService.kt
  app/src/main/java/com/talkable/data/dto/request/RequestGptDto.kt
  app/src/main/java/com/talkable/data/dto/response/ResponseGptDto.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackLoadingFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/feedback/model/FeedbackExpressionModel.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
Labels: 🐱 소현, ⭐ [FEAT]

#65 [Feature/#61] TTS 구현
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackLoadingFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable-xhdpi/img_challenge_fertilizer.png
  app/src/main/res/drawable-xhdpi/img_challenge_medicine.png
  app/src/main/res/drawable-xhdpi/img_challenge_secret.png
  app/src/main/res/drawable-xhdpi/img_challenge_shovel.png
  app/src/main/res/drawable-xhdpi/img_challenge_sun.png
  app/src/main/res/drawable-xhdpi/img_challenge_water.png
  app/src/main/res/drawable-xhdpi/img_challenge_wind.png
  app/src/main/res/drawable-xxhdpi/img_challenge_fertilizer.png
  app/src/main/res/drawable-xxhdpi/img_challenge_medicine.png
  app/src/main/res/drawable-xxhdpi/img_challenge_secret.png
  app/src/main/res/drawable-xxhdpi/img_challenge_shovel.png
  app/src/main/res/drawable-xxhdpi/img_challenge_sun.png
  app/src/main/res/drawable-xxhdpi/img_challenge_water.png
  app/src/main/res/drawable-xxhdpi/img_challenge_wind.png
  app/src/main/res/drawable/img_challenge_fertilizer.png
  app/src/main/res/drawable/img_challenge_medicine.png
  app/src/main/res/drawable/img_challenge_secret.png
  app/src/main/res/drawable/img_challenge_shovel.png
  app/src/main/res/drawable/img_challenge_sun.png
  app/src/main/res/drawable/img_challenge_water.png
  app/src/main/res/drawable/img_challenge_wind.png
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_talk_guide.xml
  app/src/main/res/layout/view_talk_speech.xml
Labels: ⭐ [FEAT], 🐰 유진

#66 #64 [FIX] : fix loading state
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
Labels: 🐱 소현, 🔨 [FIX]
