Repository TeamTalkable/ANDROID, pull requests merged in 2024-10, with the labels that each got.

#69 [Feature/#67] 피드백 문장 적용
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackLoadingFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/layout/view_talk_feedback.xml
Labels: 🐰 유진, 💟 [UI]

#72 [Feature/#71] : ai talk feedback 수정 부분 반영
  app/src/main/java/com/talkable/data/dto/response/ResponseGptDto.kt
  app/src/main/java/com/talkable/presentation/FeedbackTextColor.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackLoadingFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐱 소현, ⭐ [FEAT]

#75 [Feature/#74] Google Cloud STT API 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/java/com/talkable/presentation/talk/VoiceRecorder.kt
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 🐰 유진

#77 [Feature/#73] : firebase setting 및 발음 api 연결
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/talkable/data/ApiFactory.kt
  app/src/main/java/com/talkable/data/FirebaseFactory.kt
  app/src/main/java/com/talkable/data/api/PronunciationApiService.kt
  app/src/main/java/com/talkable/data/dto/request/RequestPronunciationDto.kt
  app/src/main/java/com/talkable/data/dto/response/ResponsePronunciationDto.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/FinalTalkFeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackDecorator.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/TalkFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/mapper/TalkFeedbackMapper.kt
  app/src/main/java/com/talkable/presentation/talk/feedback/model/TalkFeedbackModel.kt
  app/src/main/res/drawable/ic_talk_next_arrow.xml
  app/src/main/res/layout/bottom_sheet_talk_feedback.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐱 소현, ⭐ [FEAT]

#79 [Feature/#68] 리뷰 페이지 UI
  app/src/main/java/com/talkable/presentation/MainActivity.kt
  app/src/main/java/com/talkable/presentation/mypage/feedback/MyFeedbackFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/SavedWordFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/saved/model/SavedWordViewModel.kt
  app/src/main/java/com/talkable/presentation/review/ReviewFragment.kt
  app/src/main/res/drawable/ic_review_auto.xml
  app/src/main/res/drawable/ic_review_flashcards.xml
  app/src/main/res/drawable/ic_review_meaning.xml
  app/src/main/res/drawable/ic_review_selected.xml
  app/src/main/res/drawable/ic_review_spelling.xml
  app/src/main/res/drawable/ic_review_unselected.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/sel_nav_selected_review.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/view_my_page_app_bar.xml
  app/src/main/res/layout/view_review_saved.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🐰 유진, 💟 [UI]

#82 [Feature/#80] 대화 페이지 UI 수정
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable/ic_talk_help.xml
  app/src/main/res/drawable/ic_talk_speak_selected.xml
  app/src/main/res/drawable/ic_talk_speak_unselected.xml
  app/src/main/res/drawable/sel_talk_speak_btn.xml
  app/src/main/res/layout/fragment_talk.xml
Labels: 🐰 유진, 💟 [UI]

#83 [Feature/#81] 피드백 반영 UI 수정
  app/src/main/java/com/talkable/presentation/challenge/ChallengeDialog.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/talkable/presentation/challenge/ChallengeRecruitmentAdapter.kt
  app/src/main/java/com/talkable/presentation/challenge/RecruitmentViewHolder.kt
  app/src/main/java/com/talkable/presentation/login/AgreementFragment.kt
  app/src/main/res/drawable/ic_challenge_dot.xml
  app/src/main/res/drawable/sel_agreement_txt_color.xml
  app/src/main/res/drawable/shape_font5_line_2_rect.xml
  app/src/main/res/layout/fragment_agreement.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/view_challenge_ranking.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 유진, 💟 [UI]

#84 [Feature/#78] : 피드백, 알림 설정 ui 수정
  app/src/main/java/com/talkable/core/util/Const.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackExpressionFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackLoadingFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackPronunciationFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackTabAdapter.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackTabFragment.kt
  app/src/main/java/com/talkable/presentation/feedback/FeedbackViewModel.kt
  app/src/main/java/com/talkable/presentation/feedback/model/FeedbackExpressionModel.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageCalendarAdapter.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/talkable/presentation/mypage/viewholder/MyPageCalendarViewHolder.kt
  app/src/main/java/com/talkable/presentation/onboarding/AlarmSettingDialog.kt
  app/src/main/java/com/talkable/presentation/onboarding/AlarmSettingFragment.kt
  app/src/main/java/com/talkable/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/talkable/presentation/onboarding/model/User.kt
  app/src/main/java/com/talkable/presentation/onboarding/type/DayOfWeek.kt
  app/src/main/java/com/talkable/presentation/quiz/QuizAutoFragment.kt
  app/src/main/java/com/talkable/presentation/review/ReviewFragment.kt
  app/src/main/java/com/talkable/presentation/talk/TalkFragment.kt
  app/src/main/res/drawable-xhdpi/img_onboarding_fifth.png
  app/src/main/res/drawable-xhdpi/img_onboarding_first.png
  app/src/main/res/drawable-xhdpi/img_onboarding_fourth.png
  app/src/main/res/drawable-xhdpi/img_onboarding_second.png
  app/src/main/res/drawable-xhdpi/img_onboarding_third.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_fifth.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_first.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_fourth.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_second.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_third.png
  app/src/main/res/drawable/img_onboarding_fifth.png
  app/src/main/res/drawable/img_onboarding_first.png
  app/src/main/res/drawable/img_onboarding_fourth.png
  app/src/main/res/drawable/img_onboarding_second.png
  app/src/main/res/drawable/img_onboarding_third.png
  app/src/main/res/drawable/shape_main3_line_4_rect.xml
  app/src/main/res/drawable/shape_white_fill_top_bl_20_rec.xml
  app/src/main/res/drawable/shape_white_fill_top_br_20_rec.xml
  app/src/main/res/layout/dialog_select_alarm_time.xml
  app/src/main/res/layout/fragment_feedback_pronunciation.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_setting_alarm.xml
  app/src/main/res/layout/fragment_talk.xml
  app/src/main/res/layout/fragment_talk_feedback_expression.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/layout/item_talk_feedback_learned_grammar.xml
  app/src/main/res/layout/view_app_bar.xml
  app/src/main/res/layout/view_talk_feedback_app_bar.xml
  app/src/main/res/layout/view_talk_feedback_part.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/textAppearances.xml
Labels: 🐱 소현, 💟 [UI]
